### PR TITLE
DSL-30: Add Reactive Streams support

### PR DESCRIPTION
**Pull request by artembilan**
Fixes: https://github.com/spring-projects/spring-integration-java-dsl/issues/30

### CODE REVIEW

**Comment by artembilan** [comment]
@smaldini, take a look, please.
The `ReactiveStreamsTests` is for you to demonstrate on your talk.

Review is welcome anyway! :smile:

**Comment by artembilan** [comment]
Pushed the final solution. Only the `optional` tests in the `PublisherIntegrationFlowVerification` are ignored, since our `Publisher` support broadcast only in the case of `PublishSubscribeChannel` and unbounded (`Long.MAX_VALUE`) `request(n)`.

I've added `Lifecycle` to our `PublisherIntegrationFlow` to control message handling as it is done with typical SI endpoints and allow to perform `subscriber.onComplete()` at runtime manually.

@smaldini, I'd be glad to see your comments.
Thank you for collaboration anyway!

Need todo JavaDocs to this PR.
And explain the feature in the Reference Manual.

**Comment by artembilan** [comment]
@@smaldini, I've just pushed `bounded subscribable subscription`.
Since you haven't provided any comment here yet, I amended commits.

Wait for your feedback anyway.

Thank you in advance!

**Comment by artembilan** [comment]
@garyrussell , you can review if you'd like, but I think it is more important to release for IO-2.0 as is.
At least we are fine now with all this changes.

@wilkinsona , let us know how quickly you need SI-Java-DSL release which is compatible with IO-2.0.

Thanks

**Comment by garyrussell** [comment]
Polishing here: https://github.com/garyrussell/spring-integration-java-dsl/commit/9954fa402803fa2749f410fee92402555bded3cc

**Comment by artembilan** [comment]
Nothing to complain about.
Thanks!

**Comment by garyrussell** [comment]
Merged as 0ba65b2963f28c16ac22ae0326a9090e57941558

**Comment by wilkinsona** [comment]
There's no immediate need for an IO 2.0 compatible release. It looks like other parts of the Platform won't be compatible till after Spring Framework 4.2 GAs.

**Pull request closed without merging**
