### PR TITLE
Use a handler/service activator within an enricher

### PR DESCRIPTION
**Pull request by chiknrice**
The current enricher allows for specifying a payload, request and response channel where one can request additional data for enriching content or header. This change would allow one to specify an inline call to a handler instead of a request/response channel to grab the additional data.

### CODE REVIEW

**Comment by artembilan** [comment]
Hello, @chiknrice !

Thank you very much for the contribution effort!

Before we review your work, let us know if you really need this `sub-flow` feature in the current Java DSL `1.2.x` version or it can simply go to the Spring Integration `5.0` as long as the DSL has moved there [already](https://jira.spring.io/browse/INT-4133).

Thanks

**Comment by chiknrice** [comment]
Hi, I'm currently doing a bunch of publish-subscribe/aggregate to work around it but I don't mind if the change just go to 5.0.

Do you need me to port the changes to that repository?

**Comment by artembilan** [comment]
Yes, please.
Move the solution to that project.
Thanks

**Comment by artembilan** [comment]
Superseded with https://github.com/spring-projects/spring-integration/pull/2097

**Pull request closed without merging**
