### PR TITLE
INTEXT-198: Add `defaultReplyTo` to AmqpInbound

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INTEXT-198

### CODE REVIEW

**Comment by artembilan** [comment]
@garyrussell , I wonder if there are some other options which have been introduced since SI-4.2, but they are missed still in the DSL.

Don't you remember anything?

Thanks

**Comment by garyrussell** [comment]
Best to go through the change log, I guess.

**Comment by artembilan** [comment]
Yes, that's my intention to go...

**Comment by artembilan** [comment]
OK. One of them is `amqpTemplate` for the same `AmqpInboundGateway`.
Can be covered with this PR: will be pushed soon...

**Comment by artembilan** [comment]
Pushed

**Comment by artembilan** [comment]
Pushed some other fixes and lucky catch for the JMX issue with SI-4.2.1.
See https://jira.spring.io/browse/INT-3831

**Comment by artembilan** [comment]
Pushed  `JmsOutboundGateway.idleReplyContainerTimeout` property

**Comment by artembilan** [comment]
Pushed `subscriptionShared`

**Comment by artembilan** [comment]
Pushed `remoteDirectoryExpression`

**Comment by artembilan** [comment]
Pushed `appendNewLine`

**Comment by artembilan** [comment]
Pushed upgrade to 4.2.1

**Comment by garyrussell** [comment]
Merged as ca18a83902de075d3489dc610be4692b62d31456

**Pull request closed without merging**
