### PR TITLE
Start the version 1.2

### PR DESCRIPTION
**Pull request by artembilan**
Fixes GH-61 (https://github.com/spring-projects/spring-integration-java-dsl/issues/61)

### CODE REVIEW

**Comment by artembilan** [comment]
Do not merge yet.
Only after https://github.com/spring-projects/spring-integration/pull/1723
And confirmation that the provided test is fine.

**Comment by garyrussell** [comment]
Since we're not backporting the SI fix; I guess this is deferred until 1.2 ?

**Comment by artembilan** [comment]
As I think so.
No reason to upgrade to SI-4.3 and be afraid if we are still compatible with 4.2

**Comment by artembilan** [comment]
Repushed according our recent discussion: starting the `version 1.2`.
See commit message.

**Comment by garyrussell** [comment]
I don't understand your comment, 1.2 is a minor release, not a point release, so we can move to 2.0 no problem.

What am I missing?

**Comment by artembilan** [comment]
M-m-m.
Sorry, I still mixing terminology for those numbers in the `version` :smile: 

But from other hand I'm not sure that we really can upgrade to the major dependency version from our minor version.

I worry that someone will complain that we don't support the previous Kafka version...
When we move DSL into the SI-5.0 we definitely will drop that backward compatibility.

WDYT?

**Comment by garyrussell** [comment]
Makes sense.

**Pull request merged**
