### PR TITLE
DSL-24: Add Kafka Namespace Factory

### PR DESCRIPTION
**Pull request by artembilan**
Fixes: https://github.com/spring-projects/spring-integration-java-dsl/issues/24

CC @mbogoevici , @joshlong

### CODE REVIEW

**Comment by artembilan** [comment]
Pushed the fix for SF versions inconsistency from SI with Boot.
We really must release some `4.1.x` with upgrades.

There is need to add JavaDocs, though. So, don't merge yet, but feedback is appreciating.

**Comment by artembilan** [comment]
Pushed JavaDocs.
So, it is ready to merge now.

**Comment by artembilan** [comment]
Pushed more fixes

**Comment by artembilan** [comment]
Pushed one more fix for `KafkaTests`

**Comment by artembilan** [comment]
Pushed upgrade for dependencies

**Comment by artembilan** [comment]
Push optimization for tests output: avoid SOUT as much as possible

**Comment by garyrussell** [comment]
Merged as 14a398444fff8b00e7f401e3ef804c4ed4312cfa

**Pull request closed without merging**
