### PR TITLE
Add a filter() overloaded method that accepts a SpEL expression and a FilterEndpointSpec too.

### PR DESCRIPTION
**Pull request by gdelprete**
Add a filter() overloaded method that accepts a SpEL expression and a FilterEndpointSpec too.

Could not run unit test as my setup currently does not allow me to use JDK 8, but I hardly expect any impact with this change... that said, caveat developer :)

UPDATE: Would it be possible to include it in the next released version?

### CODE REVIEW

**Comment by artembilan** [comment]
@gdelprete , thank you for the PR, but before we take a look to your work, you should confirm that you have signed CLA: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md
And the PR against top-level branch, not `master`

**Comment by gdelprete** [comment]
Top level branch you mean the 1.0.x branch?

**Comment by garyrussell** [comment]
He meant topic branch - see [A Day in the Life of a Contributor](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md#a-day-in-the-life-of-a-contributor) and be sure to "sign" the [CLA](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md#sign-the-contributor-license-agreement).

**Comment by artembilan** [comment]
> UPDATE: Would it be possible to include it in the next released version?

@gdelprete , yes, we definitely will include it to the `1.1` release (somewhere this summer). Until that you can use this workaround:
````java
.filter(new ExpressionEvaluatingSelector("payload instanceOf String"), 
                   e -> e.id("filter")
````
Maybe that was a reason why I haven't included this your fix to the original implementation...

**Comment by gdelprete** [comment]
@garyrussell ok, so you mean create a topic branch. Can I name it however I want? There's no ticket for this enhancement. Also, which branch do I base the topic branch on? Master or 1.0.x ?

@artembilan is it really impossible to have a 1.0.2 release? I am waiting for the fix in #13 .

**Comment by artembilan** [comment]
@gdelprete , OK. Let it be: we'll include it to the `1.0.2`.

Anyway you should confirm that you have signed CLA for the PR acceptance.

Yes, would be better to create a GH ticket on the matter and make branch with the name based on the number of that GH issue. Of course, if you are still going to push a change to the Framework. Otherwise we'll do that for you.

Just let us know!

**Comment by gdelprete** [comment]
See PR #18

**Pull request closed without merging**
